### PR TITLE
Nodesass includePath: exporting the library

### PR DESCRIPTION
**Pull request by ghost**
A handy trick to better export and thus import this sass library without having to hard code the package location. In this way I can easily require this package from the `node_modules` library and include it in my project as fast as possible and without toil.

Example of my `Gruntfile.js` configuration:

```js
module.exports = function( grunt ) {
  require( "load-grunt-tasks" )( grunt );

  // sass includes
  var bourbon   = require( "bourbon" ).includePaths,
      normalize = require( "node-normalize-scss" ).includePaths,
      webFonts  = require( "sass-web-fonts" ).includePaths;

  grunt.initConfig( {

    sass: {
      dist: {
        files: {
          "test/css/master.css": "test/css/master.scss"
        },
        options: {
          sourceMap: true,
          outputStyle: "expanded",
          sourceComments: true,

          includePaths: [
            bourbon,
            normalize,
            webFonts
          ]
        }
      }
    }

    ...
  }
}
```

And in my sass project I just have to call the `@include` function

```scss
@charset "UTF-8";

// External sass modules
@import "bourbon";
@import "normalize";;
@import "web-fonts";
```

You can also check what others did like the well known packages I mentioned before:

- [Bourbon](https://github.com/thoughtbot/bourbon/blob/master/index.js)
- [node-normalize-scss](https://github.com/ranjandatta/node-normalize-scss/blob/master/index.js)

### CODE REVIEW

**Comment by alyssais** [comment]
Thanks for the PR!

Does `@import “web-fonts/compat”;` still work with this change?

**Comment by alyssais** [comment]
Also, would you mind adding information about how to do this to the README?

**Comment by dcdeiv** [comment]
I've fixed the compat path! And now it can be included with `@import "web-fonts/compat";`
Tested and working awesomely!

I've also added some docs!

**Comment by alyssais** [comment]
Wonderful, thank you!

**Comment by alyssais** [comment]
I'll do a version bump and release when I'm back at a computer with the appropriate credentials.

**Comment by alyssais** [comment]
Released as 2.1.0 :)

**Pull request merged**
